export function createLibraryApi(actions) {
  return {
    ...actions,
    books: {
      getAll: actions.getBooks,
      getById: actions.getBook,
      getByRFID: actions.getBookByRFID,
      search: actions.searchBooks,
      create: actions.createBook,
      update: actions.updateBook,
      archive: actions.archiveBook,
    },
    members: {
      getAll: actions.getMembers,
      getById: actions.getMember,
      create: actions.createMember,
      update: actions.updateMember,
      archive: actions.archiveMember,
      search: actions.searchMembers,
    },
    circulation: {
      issueBook: actions.issueBook,
      returnBook: actions.returnBook,
      renewBook: actions.renewBook,
      getActiveLoans: actions.getActiveLoans,
      getHistory: actions.getLoanHistory,
    },
    reservations: {
      getAll: actions.getReservations,
      create: actions.createReservation,
      cancel: actions.cancelReservation,
      approve: actions.approveReservation,
      fulfill: actions.fulfillReservation,
    },
    fines: {
      getAll: actions.getFines,
      pay: actions.payFine,
      waive: actions.waiveFine,
      reversePayment: actions.reverseFinePayment,
    },
    rfid: {
      scan: actions.scanRFID,
      lookup: actions.lookupRFID,
      register: actions.registerRFID,
      validate: actions.validateRFID,
      getLogs: actions.getRFIDLogs,
      getDevices: actions.getRFIDDevices,
    },
    inventory: {
      getStatus: actions.getInventoryStatus,
      startAudit: actions.startInventoryAudit,
      scanAudit: actions.scanInventoryRFID,
      completeAudit: actions.completeInventoryAudit,
      markLost: actions.markBookLost,
      markDamaged: actions.markBookDamaged,
      markFound: actions.markBookFound,
      changeLocation: actions.changeBookLocation,
    },
    acquisitions: {
      getAll: actions.getAcquisitions,
      create: actions.createAcquisition,
      update: actions.updateAcquisition,
      receive: actions.receiveAcquisition,
      cancel: actions.cancelAcquisition,
    },
    notifications: {
      getAll: actions.getNotifications,
      markAsRead: actions.markNotificationRead,
      markAllAsRead: actions.markAllNotificationsRead,
    },
    reports: {
      getCollection: actions.getBooks,
      getCirculation: actions.getLoanHistory,
      getOverdue: actions.getActiveLoans,
      getMembers: actions.getMembers,
      getReservations: actions.getReservations,
      getFines: actions.getFines,
      getRFID: actions.getRFIDLogs,
      getInventory: actions.getInventoryStatus,
      getAcquisitions: actions.getAcquisitions,
    },
    users: {
      getAll: () => actions.getState().users,
      getCurrent: () => actions.getState().currentUser,
      updateProfile: actions.updateProfile,
      logout: actions.logout,
    },
    settings: { get: actions.getSettings, update: actions.updateSettings, reset: actions.resetDemoData },
    profile: { update: actions.updateProfile, logout: actions.logout },
  }
}
