export function createLibraryApi(actions) {
  return {
    ...actions,
    getBooks: actions.getBooks,
    getBookById: actions.getBook,
    createBook: actions.createBook,
    updateBook: actions.updateBook,
    deleteBook: actions.archiveBook,
    getStudents: actions.getMembers,
    getStudentById: actions.getMember,
    createStudent: actions.createMember,
    updateStudent: actions.updateMember,
    deleteStudent: actions.archiveMember,
    issueBook: actions.issueBook,
    returnBook: actions.returnBook,
    getCirculationRecords: actions.getLoanHistory,
    getStudentHistory: actions.getMemberHistory,
    getBookCurrentHolder: (bookId) => actions.getLoansByBookCopy(bookId).find((record) => record.status === 'Issued') || null,
    books: {
      getAll: actions.getBooks,
      getById: actions.getBook,
      getBookById: actions.getBook,
      getByRFID: actions.getBookByRFID,
      search: actions.searchBooks,
      getCopies: actions.getBookCopies,
      getQuantities: actions.getBookQuantities,
      getCurrentHolders: actions.getBookCurrentHolders,
      getHistory: actions.getBookHistory,
      create: actions.createBook,
      update: actions.updateBook,
      archive: actions.archiveBook,
      delete: actions.archiveBook,
    },
    members: {
      getAll: actions.getMembers,
      getById: actions.getMember,
      create: actions.createMember,
      update: actions.updateMember,
      archive: actions.archiveMember,
      delete: actions.archiveMember,
      search: actions.searchMembers,
      byRFID: actions.lookupMemberRFID,
      scanRFID: actions.scanMemberRFID,
      getCurrentLoans: actions.getMemberCurrentLoans,
      getHistory: actions.getMemberHistory,
      getFines: actions.getMemberFines,
      getReservations: actions.getMemberReservations,
    },
    circulation: {
      issueBook: actions.issueBook,
      validateIssue: actions.validateIssue,
      returnBook: actions.returnBook,
      renewBook: actions.renewBook,
      getActiveLoans: actions.getActiveLoans,
      getHistory: actions.getLoanHistory,
      getByMember: actions.getLoansByMember,
      getByBookCopy: actions.getLoansByBookCopy,
    },
    reservations: {
      getAll: actions.getReservations,
      create: actions.createReservation,
      cancel: actions.cancelReservation,
      approve: actions.approveReservation,
      reject: actions.rejectReservation,
      fulfill: actions.fulfillReservation,
    },
    fines: {
      getAll: actions.getFines,
      pay: actions.payFine,
      payOwnFine: actions.payOwnFine,
      waive: actions.waiveFine,
      reversePayment: actions.reverseFinePayment,
    },
    rfid: {
      scan: actions.scanRFID,
      scanMember: actions.scanMemberRFID,
      lookupMember: actions.lookupMemberRFID,
      lookup: actions.lookupRFID,
      register: actions.registerRFID,
      validate: actions.validateRFID,
      getLogs: actions.getRFIDLogs,
      getDevices: actions.getRFIDDevices,
    },
    inventory: {
      getStatus: actions.getInventoryStatus,
      startAudit: actions.startInventoryAudit,
      scanAudit: actions.scanInventoryRFID,
      completeAudit: actions.completeInventoryAudit,
      markLost: actions.markBookLost,
      markDamaged: actions.markBookDamaged,
      markFound: actions.markBookFound,
      changeLocation: actions.changeBookLocation,
    },
    acquisitions: {
      getAll: actions.getAcquisitions,
      create: actions.createAcquisition,
      update: actions.updateAcquisition,
      receive: actions.receiveAcquisition,
      cancel: actions.cancelAcquisition,
    },
    suppliers: {
      getAll: actions.getSuppliers,
      create: actions.createSupplier,
      update: actions.updateSupplier,
      delete: actions.deleteSupplier,
    },
    notifications: {
      getAll: actions.getNotifications,
      markAsRead: actions.markNotificationRead,
      markAllAsRead: actions.markAllNotificationsRead,
    },
    reports: {
      getCollection: (query) => actions.getReport('Books', query),
      getCirculation: (query) => actions.getReport('Circulation', query),
      getOverdue: (query) => actions.getReport('Overdue', query),
      getMembers: (query) => actions.getReport('Members', query),
      getReservations: (query) => actions.getReport('Reservations', query),
      getFines: (query) => actions.getReport('Fines', query),
      getInventory: (query) => actions.getReport('Inventory', query),
      getRFID: actions.getRFIDLogs,
      getAcquisitions: (query) => actions.getReport('Acquisitions', query),
    },
    analytics: { get: actions.getAnalytics },
    users: {
      getAll: actions.getUsers,
      getCurrent: () => actions.getState().currentUser,
      updateProfile: actions.updateProfile,
      logout: actions.logout,
    },
    settings: { get: actions.getSettings, update: actions.updateSettings },
    profile: { update: actions.updateProfile, logout: actions.logout },
  }
}
