export const PERMISSIONS = {
  ADMIN: ['*'],
  LIBRARIAN: [
    'BOOK_VIEW', 'BOOK_CREATE', 'BOOK_EDIT', 'BOOK_DELETE', 'RFID_SCAN', 'RFID_REGISTER', 'RFID_MANAGE',
    'MEMBER_VIEW', 'MEMBER_CREATE', 'MEMBER_EDIT', 'MEMBER_DELETE', 'ISSUE_BOOK', 'RETURN_BOOK', 'RENEW_BOOK',
    'RESERVATION_CREATE', 'RESERVATION_MANAGE', 'FINE_VIEW', 'FINE_PAY', 'FINE_WAIVE',
    'INVENTORY_VIEW', 'INVENTORY_AUDIT', 'ACQUISITION_VIEW', 'ACQUISITION_MANAGE',
    'REPORT_VIEW', 'REPORT_EXPORT', 'ANALYTICS_VIEW', 'AUDIT_VIEW', 'PROFILE_EDIT',
  ],
  ASSISTANT_LIBRARIAN: [
    'BOOK_VIEW', 'BOOK_CREATE', 'BOOK_EDIT', 'RFID_SCAN', 'RFID_REGISTER',
    'MEMBER_VIEW', 'MEMBER_CREATE', 'MEMBER_EDIT', 'ISSUE_BOOK', 'RETURN_BOOK', 'RENEW_BOOK',
    'RESERVATION_CREATE', 'RESERVATION_MANAGE', 'FINE_VIEW', 'FINE_PAY',
    'INVENTORY_VIEW', 'INVENTORY_AUDIT', 'ACQUISITION_VIEW', 'REPORT_VIEW', 'REPORT_EXPORT',
    'ANALYTICS_VIEW', 'PROFILE_EDIT',
  ],
  FACULTY: ['BOOK_VIEW', 'RESERVATION_CREATE', 'RENEW_BOOK', 'FINE_VIEW', 'PROFILE_EDIT'],
  STUDENT: ['BOOK_VIEW', 'RESERVATION_CREATE', 'RENEW_BOOK', 'FINE_VIEW', 'PROFILE_EDIT'],
}

export function hasPermission(role, permission) {
  const permissions = PERMISSIONS[role] || []
  return permissions.includes('*') || permissions.includes(permission)
}

export function getRoleForAccount(role) {
  return ({
    Administrator: 'ADMIN',
    Librarian: 'LIBRARIAN',
    'Assistant Librarian': 'ASSISTANT_LIBRARIAN',
    Faculty: 'FACULTY',
    Student: 'STUDENT',
  })[role] || role
}
